name: Hot Auto Update

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Requests
        run: pip install requests

      - name: Run Update Script
        run: python Update_playlist.py

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Zoh.m3u
          git commit -m "Updated Asianet Links" || exit 0
          git push
