name: Zoh

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

concurrency:
  group: playlist-update
  cancel-in-progress: true

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download and Update Playlist
        run: |
          curl -L "https://jalworldiptv.vercel.app" -o Zoh.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          git add Zoh.txt
          
          if git diff --staged --quiet; then
            echo "No changes found in Zoh.txt."
          else
            git commit -m "chore: update Zoh.txt with latest content"
            git pull --rebase origin main
            git push origin main
          fi
